const express = require("express");
const auth_router = require("./auth.route");
const airports_router = require("./airports.route");
const recent_router = require("./recentSearch.route");
const flight_offer_router = require("./flightOffer.route");
const banner_router = require("./banner.route");
const testimonial_router = require("./testimonial.route");
const trending_gateway_router = require("./trendingGatway.route");
const myservice_router = require("./myService.route");
const offers_router = require("./offers.route");
const hotelPackage_router = require("./hotelPackage.route");
const HotelWithDeal_router = require("./hotelswithDeal.route");
const hotelsearch_router = require("./hotelSearch.route");
const ShootingRange_router = require("./shootingRange.route");
const support_router = require("./supports.route");
const myTrip_router = require("./mytrip.route");
const gallery_router = require("./gallery.route");
const transportService_router = require("./transport.route");
const hotelListing_router = require("./hotelListing.route");
const yh_hotels_router = require("./yhHotels.route");
const admin_auth_router = require("./admin.auth.route");
const profile_router = require("./profile.route");
const transportlist_router = require("./transportListing.auth");
const user_router = require("./user.route");
const razorpay_router = require("./razorpay.route");
const booking_router = require("./bookings.route");
const partners_router = require("./partner.route");
const router = express.Router();

router.use(auth_router);
router.use(airports_router);
router.use(recent_router);
router.use(flight_offer_router);
router.use(banner_router);
router.use(testimonial_router);
router.use(trending_gateway_router);
router.use(myservice_router);
router.use(offers_router);
router.use(hotelPackage_router);
router.use(HotelWithDeal_router);
router.use(hotelsearch_router);
router.use(ShootingRange_router);
router.use(support_router);
router.use(myTrip_router);
router.use(gallery_router);
router.use(transportService_router);
router.use(hotelListing_router);
router.use(yh_hotels_router);
router.use(admin_auth_router);
router.use(profile_router);
router.use(transportlist_router);
router.use(user_router);
router.use(razorpay_router);
router.use(booking_router);
router.use(partners_router);

module.exports = router;
